app/core/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from app.core.tools import get_configurations, send_message, save_settings, get_user_settings
from app.core.validations import ValidateConfig
from app import app


core_blueprint = Blueprint('core', __name__, template_folder='templates',
                           static_folder='static', static_url_path='/%s' % __name__)

extra = core_blueprint


@extra.route(r'/', methods=['GET'])
def index():
    context = {}

    message = session.get('message')
    if message is not None:
        context['msg'] = message
        del session['message']

    if request.method == 'GET':
        context = get_user_settings(context, request.remote_addr)

        return render_template('core/base.html',
                               context=context, colors=context.get('colors'))


@extra.route(r'/recall', methods=['POST'])
def recall():
    session['message'] = 'So small e-mail, retry'
    get = request.form.get
    title = get('title')
    message = get('message')
    if len(title) > 3 and len(message) > 10:
        send_message(title, message)
        session['message'] = 'Thank you for helping'
    return redirect(url_for('core.index'))


@extra.route(r'/settings', methods=['POST'])
def settings():
    if request.method == 'POST':
        session['message'] = 'Bad Settings'

        data = get_configurations(request)
        validate = ValidateConfig()
        if validate(data):
            ip = request.remote_addr
            save_settings(data, ip)
            session['message'] = 'Settings saved for yours IP'

        return redirect(url_for('core.index'))


@app.errorhandler(404)
def not_found(error):
    print(error)
    return render_template('404.html')

app/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Klark</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='core/css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='core/css/main.css') }}">
    <script src="{{ url_for('static', filename='lib/js/jquery-1.12.2.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/js/socket.io.min.js') }}"></script>
</head>
<body>

{% include 'core/wrapper.html' %}
{% include 'core/fix-wrapper.html' %}

<script src="{{ url_for('static', filename='core/js/main.js') }}"></script>
<script src="{{ url_for('static', filename='core/js/handling.js') }}"></script>
</body>
</html>

app/templates/core/board.html
<table class="wall-games" border="1">
    <tr class="legend">
        <td>Game ID</td>
        <td>Opponent</td>
        <td>Board size</td>
        <td>Quantity to win</td>
        <td>Permissions</td>
        <td>Join</td>
    </tr>
    {% for x in context['gamerooms'] %}
        {% if x['win'] == '-1' %}
            <tr id="{{ x['game_id'] }}">
                <td>{{ x['game_id'] }}</td>
                <td>{{ x['player1'] }}</td>
                <td>{{ x['q_size'] }}</td>
                <td>{{ x['q_count'] }}</td>
                <td>{{ x['rules'][0]|upper }} {{ x['rules'][2]|upper }} {{ x['rules'][4]|upper }}</td>

                <td class="start-play" onclick="startPlay(event)">
                    {% if not x['player2'] %}Play{% else %}Watch</td>{% endif %}
            </tr>
        {% endif %}

    {% endfor %}
    <tr id="1"></tr>
</table>

app/templates/core/contacts.html
<form id="re-call" action="{{ url_for('core.recall') }}" method="post">
    <label for="title-">Title :</label><br>
    <input id="title-" type="text" name="title" required><br>
    <label for="msg">Message : </label><br>
    <textarea id="msg" name="message"></textarea><br>
    <div class="d-but" onclick="sendRecall()">Send</div>
</form>

app/templates/core/fix-wrapper.html
<div class="fixed-wrapper show-div wall">
    <div class="board">
        {% include 'core/board.html' %}
    </div>
</div>
{##}
{#<div class="fixed-wrapper">#}
{#    <div class="set-board">#}
{#        {% include 'core/set-board.html' %}#}
{#    </div>#}
{#</div>#}
{##}
{#<div class="fixed-wrapper">#}
{##}
{#    <div class="cont-f">#}
{##}
{#        {% include 'core/contacts.html' %}#}
{#    </div>#}
{##}
{#</div>#}

{#<div class="fixed-wrapper">#}
    <div id="alert">{% if context['msg'] %}{{ context['msg'] }}{% endif %}</div>
{#</div>#}

app/templates/core/set-board.html
<div class="bor">

</div>

app/templates/core/settings.html
<form action="{{ url_for('core.settings') }}" method="post" class="config" id="settings">
    <div>
        <label for="nickname">~ Nickname : </label>
        <input id="nickname" type="text" name="nick" value="{{ context['nickname'] }}">

    </div>

    <div>
        <label for="q-to-win">~ Range of quantity crosses or noughts to win</label>
        <br>
        <input class="slider" id="q-to-win" type="range" min="3" max="12" step="1" name="q"
               value="{{ context['q_count'] }}">
        <input type="text" id="sl-q" title="quantity of crosses and noughts">
        <br>
    </div>
    <div>
        <label for="g-b-size">~ Game board size</label>
        <br>
        <input class="slider" id="g-b-size" type="range" min="3" max="12" step="1" name="size"
               value="{{ context['q_size'] }}">
        <input type="text" id="sl-g" title="Board size">
        <br>
    </div>


    <div class="cb-choice">
        <label>~ Permissible movement</label><br>
        {% for x, y in [('Vertical', 'v'), ('Horizontal', 'h'),('Diagonal', 'd')] %}
            <input title="{{ x }} moves" type="checkbox" name="ch-{{ y }}"
                   {% if context['rules'].get(y) %}checked{% endif %}><span>{{ x }}</span><br>
        {% endfor %}
    </div>

    <div class="board-color">
        {% for x in ['First', 'Second', 'Noughts' , 'Crosses'] %}
            <div class="{{ x[0]|lower }}-color">
                <label>~ {{ x }} Cell</label><br>
                {% for y in ['red', 'green', 'blue'] %}
                    <label for="{{ y }}-{{ x[0]|lower }}">{{ y[0]|upper }}</label>
                    <input type="range" name="{{ y }}-{{ x[0]|lower }}" id="{{ y }}-{{ x[0]|lower }}"
                           min="0" max="255" step="1" value="{{ colors[x[0]|lower][y[0]] }}">
                    <input class="in-color" id="{{ y[0] }}-{{ x[0]|lower }}"
                           title="{{ y|upper }}" type="text" maxlength="3"><br>
                {% endfor %}
            </div>
        {% endfor %}
    </div>

    <div class="symbol-f">
        <label for="noughts-">Noughts</label>
        <input id="noughts-" type="text" name="cell-1" value="{{ context['symbols'][0] }}" maxlength="1">
        <label for="crosses-">Crosses</label>
        <input id="crosses-" type="text" name="cell-2" value="{{ context['symbols'][1] }}" maxlength="1">
    </div>

    <div id="d-but-2" onclick="saveSettings()">Save my settings</div>
</form>

app/templates/core/wrapper.html
<div class="wrapper">
    <h1>Welcome to <span><a href=".">KLARK</a></span></h1>
    <div class="status">
        <p>The best way to play noughts and crosses via web</p>
        <hr>
    </div>

    <div class="play">
        <div class="out-a">
            <div class="in-a">
                <div>Play with Anybody</div>
            </div>
        </div>

        <div class="out-f">
            <div class="in-f">
                <div>Play with Friends</div>
            </div>
        </div>

    </div>

    <div class="menu-bar">
        <ul>
            <li class="bar" id="games" onclick="">Games</li>
            <li class="bar" id="sett">Settings</li>
        </ul>
        <hr class="hor-set">
        <div class="config">
            {% include 'core/settings.html' %}
        </div>
    </div>

    <span class="arrow-menu">↪</span>
    <div class="rel" onclick="showContacts()">If u find some error alert me.</div>
    <div class="author"><a href="https://github.com/LordBH/">Created By LordBH</a></div>

</div>